source 'https://rubygems.org'

gem 'rails', '3.2.22.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

# linter
gem 'rubocop', require: false

# Use nokogiri to parse HTML document
gem 'nokogiri'

# Cron jobs in Ruby
gem 'whenever', require: false

# Spreadsheet templates for Rails
gem 'axlsx_rails'

group :development, :test do
  # testing framework for Rails
  gem 'rspec-rails'
  # For setting up Ruby objects as test data
  gem 'factory_girl_rails', '~> 4.0'
end
